version: "3.9"
services:
  # Build database container
  sqltodo:
    build: ../analyted-database-todo/
    ports:
      - 1433:1433
      - 1431:1431
      - 1434:1434
    healthcheck:
      test: ["CMD", "/start/scripts/is_mssql_running.sh"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  # Build backend container
  backend:
    build: ../analyted-backend-todo/
    environment:
      - DB_HOST=sqltodo
      - DB_USERNAME=sa
      - DB_PASSWORD=yourStrong(!)Password
    depends_on:
      - sqltodo
    links:
      - sqltodo
    ports:
      - 8080:8080
    restart: on-failure
  # Build frontned container
  frontend:
    build: .
    depends_on:
      - backend
    ports:
      - 8090:8090
